#!/bin/sh

# script to burn CD's

# COMMAND OPTIONS
#  -v verbose
#  -dummy The  CD-Recorder  will  go through all steps of the
#  recording process, but the laser is turned off dur-
#  ing  this procedure.
#  -inq   Do an inquiry for the drive, print the inquiry info
#  and exit.
#  speed=# Set  the  speed factor of the writing process to #.
#  # is an integer, representing  a  multiple  of  the
#  audio speed.

echo "Enter your SUDO password when prompted;"
sudo /usr/bin/cdrecord -v speed=16 dev=ATA:1,0,0 $1
#/usr/bin/cdrecord -v dev=ATAPI:2,0,0 $1

# scsi0, ID6, 0,6,0
# scsi1, id1, 1,1,0
# scsi1, id2, 1,2,0
