#!/bin/bash

# script to view the output of an encrypted file

if [ ! -f $1 ]; then
    echo "Usage:"
    echo "gpg-less <valid readable encrypted file>"
    exit 1
fi

# Check for gnupg
GPG_BIN=$(which gpg)
if [ $? -gt 0 ]; then
    echo "ERROR: Can't find 'gpg' binary in \$PATH"
    exit 1
fi

$GPG_BIN --decrypt $1 2>/dev/null | /usr/bin/less

/bin/stty sane

clear

unset GPG_BIN

exit 0
