#!/bin/sh

FTP_SITE1=ftp://ftp.us.debian.org/debian/dists/potato/main/disks-i386/2.2.4-2000-01-03/disks-1.44/
MIRROR_DIR=/home/ftp/pub/linux/mirrors

wget -c -m -P$MIRROR_DIR --dot-style=binary $FTP_SITE1 

#wget -c -m -P/mnt/tmp --dot-style=binary $FTP_SITE2
#wget -c -m -P/mnt/tmp --dot-style=binary $FTP_SITE3 

# old sites
#FTP_SITE1="ftp://ftp.cdrom.com/pub/linux/redhat/updates/5.2/i386/"
#FTP_SITE2="ftp://ftp.cdrom.com/pub/linux/redhat/updates/5.2/noarch/"
#FTP_SITE3="ftp://ftp.cdrom.com/pub/linux/redhat/updates/5.2/images/"
